,folder_num,ref_no_slash,file_path,exception_str
0,5,radek1_otto-full-optimized-memory-footprint,../datasets\radek1_otto-full-optimized-memory-footprint\train.parquet,"Traceback (most recent call last):
  File ""D:\meng-code\data-valuation\attribute_extraction\attributes.py"", line 527, in extract_file_attributes_to_df
    report, sample_size = create_profiler_report(data, profiler_options)
  File ""D:\meng-code\data-valuation\attribute_extraction\attributes.py"", line 340, in create_profiler_report
    sample_size = min(len(data.data), MAX_NROWS)
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\base_data.py"", line 225, in __getattribute__
    returned = object.__getattribute__(self, name)
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\base_data.py"", line 70, in data
    self._load_data()
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\structured_mixins.py"", line 60, in _load_data
    self._data = self._load_data_from_file(self.input_file_path)
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\parquet_data.py"", line 102, in _load_data_from_file
    data, original_df_dtypes = data_utils.read_parquet_df(
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\data_utils.py"", line 378, in read_parquet_df
    data = data.astype(str)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\generic.py"", line 6324, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\internals\managers.py"", line 451, in astype
    return self.apply(
  File ""C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\internals\managers.py"", line 352, in apply
    applied = getattr(b, f)(**kwargs)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\internals\blocks.py"", line 511, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\dtypes\astype.py"", line 242, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\dtypes\astype.py"", line 187, in astype_array
    values = _astype_nansafe(values, dtype, copy=copy)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\dtypes\astype.py"", line 100, in _astype_nansafe
    return lib.ensure_string_array(
  File ""pandas\_libs\lib.pyx"", line 712, in pandas._libs.lib.ensure_string_array
  File ""pandas\_libs\lib.pyx"", line 757, in pandas._libs.lib.ensure_string_array
MemoryError
"
1,34,mrmorj_data-police-shootings,../datasets\mrmorj_data-police-shootings\fatal-police-shootings-data.csv,"Traceback (most recent call last):
  File ""D:\meng-code\data-valuation\attribute_extraction\attributes.py"", line 527, in extract_file_attributes_to_df
    report, sample_size = create_profiler_report(data, profiler_options)
  File ""D:\meng-code\data-valuation\attribute_extraction\attributes.py"", line 340, in create_profiler_report
    sample_size = min(len(data.data), MAX_NROWS)
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\base_data.py"", line 225, in __getattribute__
    returned = object.__getattribute__(self, name)
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\base_data.py"", line 70, in data
    self._load_data()
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\structured_mixins.py"", line 60, in _load_data
    self._data = self._load_data_from_file(self.input_file_path)
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\csv_data.py"", line 597, in _load_data_from_file
    return data_utils.read_csv_df(
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\data_utils.py"", line 323, in read_csv_df
    fo = pd.read_csv(file_path, **args)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers\readers.py"", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers\readers.py"", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers\readers.py"", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers\readers.py"", line 1679, in _make_engine
    return mapping[engine](f, **self.options)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers\c_parser_wrapper.py"", line 93, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File ""pandas\_libs\parsers.pyx"", line 555, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
"
2,41,whenamancodes_hr-employee-attrition,../datasets\whenamancodes_hr-employee-attrition\HR Employee Attrition.csv,"Traceback (most recent call last):
  File ""D:\meng-code\data-valuation\attribute_extraction\attributes.py"", line 527, in extract_file_attributes_to_df
    report, sample_size = create_profiler_report(data, profiler_options)
  File ""D:\meng-code\data-valuation\attribute_extraction\attributes.py"", line 340, in create_profiler_report
    sample_size = min(len(data.data), MAX_NROWS)
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\base_data.py"", line 225, in __getattribute__
    returned = object.__getattribute__(self, name)
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\base_data.py"", line 70, in data
    self._load_data()
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\structured_mixins.py"", line 60, in _load_data
    self._data = self._load_data_from_file(self.input_file_path)
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\csv_data.py"", line 597, in _load_data_from_file
    return data_utils.read_csv_df(
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\data_utils.py"", line 323, in read_csv_df
    fo = pd.read_csv(file_path, **args)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers\readers.py"", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers\readers.py"", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers\readers.py"", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers\readers.py"", line 1679, in _make_engine
    return mapping[engine](f, **self.options)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers\c_parser_wrapper.py"", line 93, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File ""pandas\_libs\parsers.pyx"", line 555, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
"
3,43,xwolf12_malicious-and-benign-websites,../datasets\xwolf12_malicious-and-benign-websites\dataset.csv,"Traceback (most recent call last):
  File ""D:\meng-code\data-valuation\attribute_extraction\attributes.py"", line 527, in extract_file_attributes_to_df
    report, sample_size = create_profiler_report(data, profiler_options)
  File ""D:\meng-code\data-valuation\attribute_extraction\attributes.py"", line 340, in create_profiler_report
    sample_size = min(len(data.data), MAX_NROWS)
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\base_data.py"", line 225, in __getattribute__
    returned = object.__getattribute__(self, name)
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\base_data.py"", line 70, in data
    self._load_data()
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\structured_mixins.py"", line 60, in _load_data
    self._data = self._load_data_from_file(self.input_file_path)
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\csv_data.py"", line 597, in _load_data_from_file
    return data_utils.read_csv_df(
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\data_utils.py"", line 323, in read_csv_df
    fo = pd.read_csv(file_path, **args)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers\readers.py"", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers\readers.py"", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers\readers.py"", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers\readers.py"", line 1679, in _make_engine
    return mapping[engine](f, **self.options)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers\c_parser_wrapper.py"", line 93, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File ""pandas\_libs\parsers.pyx"", line 555, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
"
4,76,kaggle_no-data-sources,../datasets\kaggle_no-data-sources\empty.csv,"Traceback (most recent call last):
  File ""D:\meng-code\data-valuation\attribute_extraction\attributes.py"", line 527, in extract_file_attributes_to_df
    report, sample_size = create_profiler_report(data, profiler_options)
  File ""D:\meng-code\data-valuation\attribute_extraction\attributes.py"", line 340, in create_profiler_report
    sample_size = min(len(data.data), MAX_NROWS)
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\base_data.py"", line 225, in __getattribute__
    returned = object.__getattribute__(self, name)
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\base_data.py"", line 70, in data
    self._load_data()
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\structured_mixins.py"", line 60, in _load_data
    self._data = self._load_data_from_file(self.input_file_path)
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\csv_data.py"", line 597, in _load_data_from_file
    return data_utils.read_csv_df(
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\data_utils.py"", line 323, in read_csv_df
    fo = pd.read_csv(file_path, **args)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers\readers.py"", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers\readers.py"", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers\readers.py"", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers\readers.py"", line 1679, in _make_engine
    return mapping[engine](f, **self.options)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers\c_parser_wrapper.py"", line 93, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File ""pandas\_libs\parsers.pyx"", line 555, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
"
5,87,robikscube_flight-delay-dataset-20182022,../datasets\robikscube_flight-delay-dataset-20182022\Combined_Flights_2018.parquet,"Traceback (most recent call last):
  File ""D:\meng-code\data-valuation\attribute_extraction\attributes.py"", line 527, in extract_file_attributes_to_df
    report, sample_size = create_profiler_report(data, profiler_options)
  File ""D:\meng-code\data-valuation\attribute_extraction\attributes.py"", line 340, in create_profiler_report
    sample_size = min(len(data.data), MAX_NROWS)
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\base_data.py"", line 225, in __getattribute__
    returned = object.__getattribute__(self, name)
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\base_data.py"", line 70, in data
    self._load_data()
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\structured_mixins.py"", line 60, in _load_data
    self._data = self._load_data_from_file(self.input_file_path)
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\parquet_data.py"", line 102, in _load_data_from_file
    data, original_df_dtypes = data_utils.read_parquet_df(
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\data_utils.py"", line 378, in read_parquet_df
    data = data.astype(str)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\generic.py"", line 6324, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\internals\managers.py"", line 451, in astype
    return self.apply(
  File ""C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\internals\managers.py"", line 352, in apply
    applied = getattr(b, f)(**kwargs)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\internals\blocks.py"", line 511, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\dtypes\astype.py"", line 242, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\dtypes\astype.py"", line 187, in astype_array
    values = _astype_nansafe(values, dtype, copy=copy)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\dtypes\astype.py"", line 100, in _astype_nansafe
    return lib.ensure_string_array(
  File ""pandas\_libs\lib.pyx"", line 712, in pandas._libs.lib.ensure_string_array
  File ""pandas\_libs\lib.pyx"", line 757, in pandas._libs.lib.ensure_string_array
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 43.4 MiB for an array with shape (5689512,) and data type object
"
6,87,robikscube_flight-delay-dataset-20182022,../datasets\robikscube_flight-delay-dataset-20182022\Combined_Flights_2019.parquet,"Traceback (most recent call last):
  File ""D:\meng-code\data-valuation\attribute_extraction\attributes.py"", line 527, in extract_file_attributes_to_df
    report, sample_size = create_profiler_report(data, profiler_options)
  File ""D:\meng-code\data-valuation\attribute_extraction\attributes.py"", line 340, in create_profiler_report
    sample_size = min(len(data.data), MAX_NROWS)
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\base_data.py"", line 225, in __getattribute__
    returned = object.__getattribute__(self, name)
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\base_data.py"", line 70, in data
    self._load_data()
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\structured_mixins.py"", line 60, in _load_data
    self._data = self._load_data_from_file(self.input_file_path)
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\parquet_data.py"", line 102, in _load_data_from_file
    data, original_df_dtypes = data_utils.read_parquet_df(
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\data_utils.py"", line 378, in read_parquet_df
    data = data.astype(str)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\generic.py"", line 6324, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\internals\managers.py"", line 451, in astype
    return self.apply(
  File ""C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\internals\managers.py"", line 352, in apply
    applied = getattr(b, f)(**kwargs)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\internals\blocks.py"", line 511, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\dtypes\astype.py"", line 242, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\dtypes\astype.py"", line 187, in astype_array
    values = _astype_nansafe(values, dtype, copy=copy)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\dtypes\astype.py"", line 100, in _astype_nansafe
    return lib.ensure_string_array(
  File ""pandas\_libs\lib.pyx"", line 712, in pandas._libs.lib.ensure_string_array
  File ""pandas\_libs\lib.pyx"", line 757, in pandas._libs.lib.ensure_string_array
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 247. MiB for an array with shape (32366736,) and data type object
"
7,87,robikscube_flight-delay-dataset-20182022,../datasets\robikscube_flight-delay-dataset-20182022\Combined_Flights_2021.parquet,"Traceback (most recent call last):
  File ""D:\meng-code\data-valuation\attribute_extraction\attributes.py"", line 527, in extract_file_attributes_to_df
    report, sample_size = create_profiler_report(data, profiler_options)
  File ""D:\meng-code\data-valuation\attribute_extraction\attributes.py"", line 340, in create_profiler_report
    sample_size = min(len(data.data), MAX_NROWS)
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\base_data.py"", line 225, in __getattribute__
    returned = object.__getattribute__(self, name)
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\base_data.py"", line 70, in data
    self._load_data()
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\structured_mixins.py"", line 60, in _load_data
    self._data = self._load_data_from_file(self.input_file_path)
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\parquet_data.py"", line 102, in _load_data_from_file
    data, original_df_dtypes = data_utils.read_parquet_df(
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\data_utils.py"", line 378, in read_parquet_df
    data = data.astype(str)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\generic.py"", line 6324, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\internals\managers.py"", line 451, in astype
    return self.apply(
  File ""C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\internals\managers.py"", line 352, in apply
    applied = getattr(b, f)(**kwargs)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\internals\blocks.py"", line 511, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\dtypes\astype.py"", line 242, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\dtypes\astype.py"", line 187, in astype_array
    values = _astype_nansafe(values, dtype, copy=copy)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\dtypes\astype.py"", line 100, in _astype_nansafe
    return lib.ensure_string_array(
  File ""pandas\_libs\lib.pyx"", line 712, in pandas._libs.lib.ensure_string_array
  File ""pandas\_libs\lib.pyx"", line 757, in pandas._libs.lib.ensure_string_array
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 241. MiB for an array with shape (31559355,) and data type object
"
8,87,robikscube_flight-delay-dataset-20182022,../datasets\robikscube_flight-delay-dataset-20182022\Combined_Flights_2022.parquet,"Traceback (most recent call last):
  File ""D:\meng-code\data-valuation\attribute_extraction\attributes.py"", line 527, in extract_file_attributes_to_df
    report, sample_size = create_profiler_report(data, profiler_options)
  File ""D:\meng-code\data-valuation\attribute_extraction\attributes.py"", line 340, in create_profiler_report
    sample_size = min(len(data.data), MAX_NROWS)
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\base_data.py"", line 225, in __getattribute__
    returned = object.__getattribute__(self, name)
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\base_data.py"", line 70, in data
    self._load_data()
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\structured_mixins.py"", line 60, in _load_data
    self._data = self._load_data_from_file(self.input_file_path)
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\parquet_data.py"", line 102, in _load_data_from_file
    data, original_df_dtypes = data_utils.read_parquet_df(
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\data_utils.py"", line 378, in read_parquet_df
    data = data.astype(str)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\generic.py"", line 6324, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\internals\managers.py"", line 451, in astype
    return self.apply(
  File ""C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\internals\managers.py"", line 352, in apply
    applied = getattr(b, f)(**kwargs)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\internals\blocks.py"", line 511, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\dtypes\astype.py"", line 242, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\dtypes\astype.py"", line 187, in astype_array
    values = _astype_nansafe(values, dtype, copy=copy)
  File ""C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\dtypes\astype.py"", line 100, in _astype_nansafe
    return lib.ensure_string_array(
  File ""pandas\_libs\lib.pyx"", line 712, in pandas._libs.lib.ensure_string_array
  File ""pandas\_libs\lib.pyx"", line 784, in pandas._libs.lib.ensure_string_array
MemoryError
"
